#!/usr/bin/env python3
# Copyright 2026 AI5Labs Research OPC Private Limited
# SPDX-License-Identifier: Apache-2.0
"""Synchronize the canonical NeMo starter bundle into the Helm package.

The canonical authoring source lives at ``rails/starter`` in the component.
Helm cannot package files outside a chart directory, so the subchart carries
generated byte-for-byte mirrors under ``files/rails/starter``. This tool is
the sole supported way to refresh those mirrors.

Use ``--check`` in CI or before review to detect an unsynchronized bundle.
"""

from __future__ import annotations

import argparse
import sys
from pathlib import Path

_FILENAMES = ("config.yml", "rails.co")
_COMPONENT_ROOT = Path(__file__).resolve().parents[1]
_REPO_ROOT = _COMPONENT_ROOT.parents[1]
_SOURCE_DIR = _COMPONENT_ROOT / "rails" / "starter"
_CHART_DIR = (
    _REPO_ROOT / "charts" / "fabric" / "charts" / "nemo-sidecar" / "files" / "rails" / "starter"
)


def _synchronize(*, check: bool) -> list[str]:
    """Return mismatched filenames; update them unless ``check`` is true."""

    mismatches: list[str] = []
    for filename in _FILENAMES:
        source = (_SOURCE_DIR / filename).read_bytes()
        destination = _CHART_DIR / filename
        current = destination.read_bytes() if destination.exists() else None
        if current == source:
            continue
        mismatches.append(filename)
        if not check:
            destination.parent.mkdir(parents=True, exist_ok=True)
            destination.write_bytes(source)
    return mismatches


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--check",
        action="store_true",
        help="fail if a packaged chart file differs; do not modify files",
    )
    args = parser.parse_args(argv)
    mismatches = _synchronize(check=args.check)
    if not mismatches:
        print("NeMo starter chart bundle is synchronized.")
        return 0
    if args.check:
        print(
            "NeMo starter chart bundle is stale: " + ", ".join(mismatches),
            file=sys.stderr,
        )
        return 1
    print("Updated NeMo starter chart bundle: " + ", ".join(mismatches))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
